/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import database.ConnectDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 84899
 */
public class DocGiaView extends javax.swing.JFrame {
    private String email;
    ConnectDB cn = new ConnectDB();
    Connection conn;
    private ResultSet rs;
    public DocGiaView(String email) {
        initComponents();
        setSize(700,600);
        initClock();
        this.email=email;
    }

     private void initClock() {
        Clock th = new Clock(lblClock);
        th.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearchBook = new javax.swing.JButton();
        btnInfor = new javax.swing.JButton();
        btnFullBook = new javax.swing.JButton();
        btnRule = new javax.swing.JButton();
        lblGreeting = new javax.swing.JLabel();
        btnChangePass = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblClock = new javax.swing.JLabel();
        btnTraSach = new javax.swing.JButton();
        btnRule2 = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnLogout = new javax.swing.JMenuItem();
        btnExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearchBook.setText("Tìm kiếm sách");
        btnSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 130, 40));

        btnInfor.setText("Thông tin độc giả");
        btnInfor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInforActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 130, 40));

        btnFullBook.setText("Thông tin sách");
        btnFullBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFullBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnFullBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 130, 40));

        btnRule.setText("Quy định");
        btnRule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRuleActionPerformed(evt);
            }
        });
        getContentPane().add(btnRule, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 130, 40));

        lblGreeting.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblGreeting.setText("Xin chào bạn đọc, bạn cần gì?");
        getContentPane().add(lblGreeting, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 360, 50));

        btnChangePass.setText("Đổi mật khẩu");
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });
        getContentPane().add(btnChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 130, 40));

        jButton1.setText("Mượn sách");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 130, 40));

        lblClock.setBackground(new java.awt.Color(204, 255, 204));
        lblClock.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblClock.setText("AM - PM");
        lblClock.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblClockAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                lblClockAncestorRemoved(evt);
            }
        });
        getContentPane().add(lblClock, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, 30));

        btnTraSach.setText("Trả sách");
        btnTraSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraSachActionPerformed(evt);
            }
        });
        getContentPane().add(btnTraSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 130, 40));

        btnRule2.setText("Quy định");
        btnRule2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRule2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRule2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 130, 40));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nen-background-trang-dep-va-don-gian_110344503.jpg"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("Hệ thống");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnLogout.setText("Đăng xuất");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(btnLogout);

        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jMenu1.add(btnExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        LoginView login = new LoginView();
        dispose();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnInforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInforActionPerformed
           conn = cn.getConnection();
        try {
            System.out.println("Da ket noi");
            String sql = "SELECT * FROM docgia WHERE EMAIL=?";
            PreparedStatement ps = (PreparedStatement) conn.prepareCall(sql);
            System.out.println(email);
            ps.setString(1,email);
            rs = ps.executeQuery();
            rs.next();
            System.out.println("Ten la:<"+rs+">");
            String maDocGia=rs.getString(1);
            String name=rs.getString(2);
            String sdt=rs.getString(3);
            String email=rs.getString(4);
            String ngaysinh=rs.getString(5);
            String cccd=rs.getString(6);
            int muon=rs.getInt(7);
            int tra=rs.getInt(8);
            String message="Mã độc giả: "+maDocGia+"\n"+ 
                            "Họ và tên: "+name+"\n"+
                            "Ngày sinh: " + ngaysinh +"\n"+
                            "Số điện thoại: "+sdt+"\n"+
                            "Số Căn cước công dân: "+ cccd+ "\n"+
                            "Email: "+email+"\n";
                        
            JOptionPane.showMessageDialog(new JFrame(), message, "Thông tin độc giả", 0x1);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnInforActionPerformed

    private void btnSearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBookActionPerformed
        Book.FRT timkiem = new Book.FRT(email);
        dispose();
        timkiem.setVisible(true);
    }//GEN-LAST:event_btnSearchBookActionPerformed

    private void btnFullBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFullBookActionPerformed
        Book.FrSach sach = new Book.FrSach(email);
        dispose();
        sach.setVisible(true);
    }//GEN-LAST:event_btnFullBookActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        ChangPass changepass = new ChangPass(email);
        dispose();
        changepass.setVisible(true);
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void btnRuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRuleActionPerformed
        
        String message1 = "1. Chỉnh sửa thông tin cá nhân: Bạn đọc vui lòng đến trưc tiếp đến thư viện \n" +
                           "2. Mượn sách:" + "\n" +
                            "  Số lượng mượn tối đa: 3 quyển/ lần mượn" + "\n" +
                            "  Thời gian mượn tối đa: 14 ngày" + "\n" +
                            "  Tiền phạt quá hạn mượn: 1000đ/1 ngày/1 quyển" + "\n" +
                            "  Nếu bạn đọc đang mượn quá 10 quyển thì không được mượn nữa \n"+
                            "3. Trả sách: \n" +
                            "  Phải đảm bảo sách không bị mất trang, dính bẩn, hư hỏng. \n" +
                            "  Nếu sách bị hư hỏng, sẽ xem xét tình trạng và có hình thức phạt";
                            
        JOptionPane.showMessageDialog(new JFrame(), message1, "Quy định thư viện", 0x1);
    }//GEN-LAST:event_btnRuleActionPerformed

    private void lblClockAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblClockAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblClockAncestorAdded

    private void lblClockAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblClockAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblClockAncestorRemoved

    private void btnTraSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraSachActionPerformed
        dispose();
        TraSachView tr = new TraSachView(email);
        tr.setVisible(true);
    }//GEN-LAST:event_btnTraSachActionPerformed

    private void btnRule2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRule2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRule2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DocGiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DocGiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DocGiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DocGiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DocGiaView("NULL").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePass;
    private javax.swing.JMenuItem btnExit;
    private javax.swing.JButton btnFullBook;
    private javax.swing.JButton btnInfor;
    private javax.swing.JMenuItem btnLogout;
    private javax.swing.JButton btnRule;
    private javax.swing.JButton btnRule2;
    private javax.swing.JButton btnSearchBook;
    private javax.swing.JButton btnTraSach;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblGreeting;
    // End of variables declaration//GEN-END:variables
}
