package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oOOo
 */
public class Tienphat extends javax.swing.JFrame {

     private DefaultTableModel tblModel;
     private DefaultTableModel tblModel1;
    /**
     * Creates new form Tienphat
     */
    public Tienphat() {
        initComponents();
        initTableModel();
        initTableModel1();
    }

     private void initTableModel(){
        String[] columnNames = new String[]{"ID độc giả", "Tên độc giả", "Tên sách", "Ngày mượn","Ngày đến hạn", "Ngày trả", "Số Ngày Quá Hạn"};
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(columnNames);
        tbdanhsach.setModel(tblModel);
    }
     
     private void initTableModel1(){
        String[] columnNames = new String[]{"Tổng tiền phạt"};
        tblModel1 = new DefaultTableModel();
        tblModel1.setColumnIdentifiers(columnNames);
        tbtienphat.setModel(tblModel1);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btntimkiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTimkiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdanhsach = new javax.swing.JTable();
        btnThoat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbtienphat = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btntimkiem.setText("Tìm Kiếm");
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });
        getContentPane().add(btntimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 63, -1, -1));

        jLabel1.setText("Nhập ID độc giả");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 66, -1, -1));
        getContentPane().add(txtTimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 63, 138, -1));

        tbdanhsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID độc giả", "Tên độc giả", "Tên sách", "Ngày mượn", "Ngày Đến Hạn", "Ngày Trả", "Số Ngày Quá Hạn"
            }
        ));
        jScrollPane1.setViewportView(tbdanhsach);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 167, 528, 229));

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, -1, -1));

        tbtienphat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tổng tiền phạt"
            }
        ));
        jScrollPane2.setViewportView(tbtienphat);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 110, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
        // TODO add your handling code here:
         try{
            String url = "jdbc:mysql://localhost/thuvien";
        var user = "root";
        var password = "";
             Connection con = DriverManager.getConnection(url, user, password);
            
            if(txtTimkiem.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Ban chua nhap gia tri tim kiem");
            }
            else{
           String sql = "select m.Madg, m.TENDOCGIA, m.TENSACH, m.NGAYMUON, m.NGAYDENHAN, m.NGAYTRA, m.SONGAYQUAHAN from phieu m WHERE  MADOCGIA = "+txtTimkiem.getText()+"";
            String sqlUpdate1 = "Update muon set NGAYDENHAN = DATE_ADD(NGAYMUON, INTERVAL 2 week) Where MADOCGIA = "+txtTimkiem.getText()+"";
             PreparedStatement pstmt2 = con.prepareStatement(sqlUpdate1);
             pstmt2.executeUpdate();
             String sqlUpdate2 = "Update muon set SONGAYQUAHAN = (NGAYTRA-NGAYDENHAN) Where MADOCGIA = "+txtTimkiem.getText()+"";
             PreparedStatement pstmt3 = con.prepareStatement(sqlUpdate2);
             pstmt3.executeUpdate();
             
           String sql1 = "select SUM(SONGAYQUAHAN)*1000 AS TIENPHAT from muon WHERE  MADOCGIA = "+txtTimkiem.getText()+"";
             PreparedStatement pstmt4 = con.prepareStatement(sql1);
             ResultSet rs1 = pstmt4.executeQuery();
             
            PreparedStatement pstmt = con.prepareStatement(sql);
           
            ResultSet rs = pstmt.executeQuery();
            
          
                tblModel.setRowCount(0);
            while(rs.next()){
                tblModel.addRow(new Object[]{
                rs.getString("MADOCGIA"),
                rs.getString("TENDOCGIA"),
                rs.getString("TENSACH"),
                rs.getDate("NGAYMUON"),
                rs.getDate("NGAYDENHAN"),
                rs.getDate("NGAYTRA"),
                rs.getInt("SONGAYQUAHAN")
            });
            }
            tblModel1.setRowCount(0);
            while(rs1.next()){
                tblModel1.addRow(new Object[]{
                rs1.getString("TIENPHAT"),
            });
            }
            tblModel1.fireTableDataChanged();
            }
        }
        
        
        catch(Exception e){
            e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btntimkiemActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tienphat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tienphat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tienphat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tienphat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tienphat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbdanhsach;
    private javax.swing.JTable tbtienphat;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
}
