/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Book;

import database.ConnectDB;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 84899
 */
public class FRT extends javax.swing.JFrame {
    private DefaultTableModel tblModel;
    private String email;
    ConnectDB cn = new ConnectDB();
    Connection conn;
    private ResultSet rs;
    public FRT(String email) {
        initComponents();
        initTableModel();
        this.email = email;
        setSize(700,600);
    }

    private void initTableModel(){
        String[] columnNames = new String[]{"Mã sách", "Tên sách", "Tác giả", "Thể loại", "Số lượng còn", "Nhà xuất bản"};
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(columnNames);
        tbSach.setModel(tblModel);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTimkiemtheoten = new javax.swing.JButton();
        btnTimkiemtheotheloai = new javax.swing.JButton();
        txtTimkiem = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSach = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnTimkiemtheotacgia = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnSystem = new javax.swing.JMenu();
        btnLogout = new javax.swing.JMenuItem();
        Thoát = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTimkiemtheoten.setText("Tìm kiếm theo tên");
        btnTimkiemtheoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemtheotenActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimkiemtheoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 150, 30));

        btnTimkiemtheotheloai.setText("Tìm kiếm theo thể loại");
        btnTimkiemtheotheloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemtheotheloaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimkiemtheotheloai, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 150, 30));

        txtTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimkiemActionPerformed(evt);
            }
        });
        getContentPane().add(txtTimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 320, 40));

        lblSearch.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSearch.setText("Tìm kiếm sách");
        getContentPane().add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 180, 50));

        tbSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbSach);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 610, 200));

        jLabel1.setText("Nhập từ khóa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        btnTimkiemtheotacgia.setText("Tìm kiếm theo tác giả");
        getContentPane().add(btnTimkiemtheotacgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 150, 30));

        btnBack.setText("< Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, -1, -1));

        btnSystem.setText("Hệ thống");
        btnSystem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnLogout.setText("Đăng xuất");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        btnSystem.add(btnLogout);

        Thoát.setText("Thoát");
        Thoát.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThoátActionPerformed(evt);
            }
        });
        btnSystem.add(Thoát);

        jMenuBar1.add(btnSystem);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimkiemActionPerformed

    private void btnTimkiemtheotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemtheotenActionPerformed
        // TODO add your handling code here:
        try{
            String url = "jdbc:mysql://localhost/quanlysach";
        var user = "root";
        var password = "";
             Connection con = DriverManager.getConnection(url, user, password);
            
            if(txtTimkiem.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Ban chua nhap gia tri tim kiem");
            }
            else{
            String sql = "select S.MASACH, S.TENSACH, S.TENTACGIA, S.TENNXB, S.THELOAI, S.SOLUONG, S.SOLUONGCONLAI, S.SOTRANG, S.MAVITRI, V.GIASACH, V.HANG from sach S, vitri V where S.MAVITRI = V.MAVITRI AND  S.TENSACH like '%"+txtTimkiem.getText()+"%'";
            
            PreparedStatement pstmt = con.prepareStatement(sql);
           
            ResultSet rs = pstmt.executeQuery();
            
          
                tblModel.setRowCount(0);
            while(rs.next()){
                tblModel.addRow(new Object[]{
                rs.getString("MASACH"),
                rs.getString("TENSACH"),
                rs.getString("TENTACGIA"),
                rs.getString("THELOAI"),
                rs.getInt("SOLUONGCONLAI"),
                rs.getInt("SOTRANG"),
                rs.getString("TENNXB"),
            });
            }
            tblModel.fireTableDataChanged();
            }
        }
        
        
        catch(Exception e){
            e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnTimkiemtheotenActionPerformed

    private void btnTimkiemtheotacgiaActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
        try{
            String url = "jdbc:mysql://localhost/quanlysach";
        var user = "root";
        var password = "";
             Connection con = DriverManager.getConnection(url, user, password);
            
            
            String sql = "select * from sach where TENTACGIA like '%"+txtTimkiem.getText()+"%'";
            
            PreparedStatement pstmt = con.prepareStatement(sql);
           
            ResultSet rs = pstmt.executeQuery();
            
            tblModel.setRowCount(0);
            while(rs.next()){
                tblModel.addRow(new Object[]{
                rs.getString("MASACH"),
                rs.getString("TENSACH"),
                rs.getString("TENTACGIA"),
                rs.getString("THELOAI"),
                rs.getString("SOLUONGCONLAI"),
                rs.getString("TENNXB"),
            });
            }
            tblModel.fireTableDataChanged();
        }
        
        
        catch(Exception e){
            e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }                                                 

    private void btnTimkiemtheotheloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemtheotheloaiActionPerformed
        // TODO add your handling code here:
        try{
            String url = "jdbc:mysql://localhost/quanlysach";
        var user = "root";
        var password = "";
             Connection con = DriverManager.getConnection(url, user, password);
            
            if(txtTimkiem != null){
            String sql = "select * from sach where THELOAI like '%"+txtTimkiem.getText()+"%'";
            
            PreparedStatement pstmt = con.prepareStatement(sql);
           
            ResultSet rs = pstmt.executeQuery();
            
            tblModel.setRowCount(0);
            while(rs.next()){
                tblModel.addRow(new Object[]{
                rs.getString("MASACH"),
                rs.getString("TENSACH"),
                rs.getString("TENTACGIA"),
                rs.getString("THELOAI"),
                rs.getString("SOLUONGCONLAI"),
                rs.getString("TENNXB"),
                        
            });
            }
            tblModel.fireTableDataChanged();
        }
            else{
                JOptionPane.showMessageDialog(this, "Ban chua nhap gia tri tim kiem");
            }
        }
        
        
        catch(Exception e){
            e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnTimkiemtheotheloaiActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        view.LoginView login = new view.LoginView();
        dispose();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void ThoátActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThoátActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ThoátActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        view.DocGiaView docgiaview = new view.DocGiaView(email);
        dispose();
        docgiaview.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRT("trang2002cool@gmail.").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Thoát;
    private javax.swing.JButton btnBack;
    private javax.swing.JMenuItem btnLogout;
    private javax.swing.JMenu btnSystem;
    private javax.swing.JButton btnTimkiemtheotacgia;
    private javax.swing.JButton btnTimkiemtheoten;
    private javax.swing.JButton btnTimkiemtheotheloai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JTable tbSach;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
}
