/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Book;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oOOo
 */
public class TraSach extends javax.swing.JFrame {

     private DefaultTableModel tblModel;
    /**
     * Creates new form TraSach
     */
    public TraSach() {
        initComponents();
        initComboBox();
        initTableModel();
    }
    
    private void initComboBox(){
        try{
            String url = "jdbc:mysql://localhost/quanlysach";
        var user = "root";
        var password = "";
             Connection con = DriverManager.getConnection(url, user, password);
             String sql = "select TENSACH from sach ";
             PreparedStatement pstmt = con.prepareStatement(sql);
              ResultSet rs = pstmt.executeQuery();
              boxSach.removeAllItems();
              while(rs.next()){
                  boxSach.addItem(rs.getString("TENSACH"));
              }
        }
        catch(Exception e){
             e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void initTableModel(){
     String[] columnNames = new String[]{"MADOCGIA", "TENDOCGIA", "TENSACH", "SOLUONG", "NGAYMUON", "NGAYTRA", "TIENPHAT"};
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(columnNames);
        tblTra.setModel(tblModel);   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnTra = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtmadocgia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        boxSach = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTra = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtsoluongtra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Trả Sách");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel2.setText("Mã độc giả");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 66, -1, -1));

        btnTra.setText("Trả sách");
        btnTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraActionPerformed(evt);
            }
        });
        getContentPane().add(btnTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, -1));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, -1, -1));
        getContentPane().add(txtmadocgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 144, -1));

        jLabel5.setText("Tên sách");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        boxSach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxSachActionPerformed(evt);
            }
        });
        getContentPane().add(boxSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        tblTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MADOCGIA", "TENDOCGIA", "TENSACH", "SOLUONG", "NGAYMUON", "NGAYTRA", "TIENPHAT"
            }
        ));
        jScrollPane1.setViewportView(tblTra);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 530, 150));

        jLabel3.setText("Số lượng trả");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        getContentPane().add(txtsoluongtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraActionPerformed
        // TODO add your handling code here:
        try{
            String url = "jdbc:mysql://localhost/quanlysach";
        var user = "root";
        var password = "";
             Connection con = DriverManager.getConnection(url, user, password);
             
             String sqlUpdate = "Update muon set NGAYTRA = CURDATE() Where MADOCGIA = "+txtmadocgia.getText()+"";
             PreparedStatement pstmt1 = con.prepareStatement(sqlUpdate);
             pstmt1.executeUpdate();
            
             String sqlUpdate1 = "Update muon set TIENPHAT = (CURDATE()-NGAYMUON-14)*1000*SOLUONGMUON Where MADOCGIA = "+txtmadocgia.getText()+" AND (CURDATE()-NGAYMUON) > 14";
             PreparedStatement pstmt2 = con.prepareStatement(sqlUpdate1);
             pstmt2.executeUpdate();
            
             String updatesoluong = "Update sach set SOLUONGCONLAI = SOLUONGCONLAI + ? Where TENSACH = ?";
            PreparedStatement pstmt3 = con.prepareStatement(updatesoluong);
            pstmt3.setInt(1, Integer.parseInt(txtsoluongtra.getText()));
            pstmt3.setString(2, boxSach.getSelectedItem().toString());
            pstmt3.executeUpdate();
            
            String sql = "select m.MADOCGIA, m.TENDOCGIA, m.TENSACH, m.SOLUONGMUON, m.NGAYMUON, m.NGAYTRA, m.TIENPHAT from muon m WHERE  MADOCGIA = "+txtmadocgia.getText()+"";
             PreparedStatement pstmt = con.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery();
             while(rs.next()){
                 tblModel.addRow(new Object[]{
                 rs.getString("MADOCGIA"),
                     rs.getString("TENDOCGIA"),
                     rs.getString("TENSACH"),
                      rs.getInt("SOLUONGMUON"),
                       rs.getDate("NGAYMUON"),
                        rs.getDate("NGAYTRA"),
                         rs.getInt("TIENPHAT"),
                     });
             }
             
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnTraActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void boxSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxSachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TraSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxSach;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnTra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTra;
    private javax.swing.JTextField txtmadocgia;
    private javax.swing.JTextField txtsoluongtra;
    // End of variables declaration//GEN-END:variables
}
