/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.qtv;

import dao.DocGiaDao;
import model.DocGiaModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import database.Clock;

/**
 *
 * @author 84899
 */
public class ThemDocGiaView extends javax.swing.JFrame {
    private DefaultTableModel tblModel;
    Connection conn;
    private ResultSet rs;
    
    public ThemDocGiaView() {
        initComponents();
        initTable();
        loadDataToTable();
        initClock();
        setSize(1000,660);
    }
    
    private void initClock() {
        Clock th = new Clock(lblClock);
        th.start();
    }
    
    private void initTable() {
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã độc giả", "Tên độc giả", "Số điện thoại", "Email", "Ngày sinh", "CCCD", "Số sách đang mượn", "Tiền phạt"});
      //  tbldg.setModel(tblModel);
    }

    private void loadDataToTable() {
        try {
            DocGiaDao dao = new DocGiaDao();
            List<DocGiaModel> list = dao.findAll();
            tblModel.setRowCount(0);
            for (DocGiaModel r : list) {
                tblModel.addRow(new Object[]{
                    r.getTendg(), r.getSodt(), r.getEmail(), r.getNgaysinh(), r.getCancuoccd(), r.getDangmuon(), r.getTienphat()
                });
            }
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblClock = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtTendg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSodt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtCC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblBirth = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setText("< Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, -1, -1));

        lblClock.setBackground(new java.awt.Color(204, 255, 204));
        lblClock.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblClock.setText("AM - PM");
        lblClock.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblClockAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                lblClockAncestorRemoved(evt);
            }
        });
        getContentPane().add(lblClock, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Thêm độc giả mới");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 170, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTendg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTendgActionPerformed(evt);
            }
        });
        jPanel1.add(txtTendg, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 150, 30));

        jLabel2.setText("Tên độc giả (*)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));
        jPanel1.add(txtSodt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 150, 30));

        jLabel3.setText("Số điện thoại (*)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 150, 30));

        lblEmail.setText("Email (*)");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));
        jPanel1.add(txtCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 150, 30));

        jLabel4.setText("Căn cước (*)");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        lblBirth.setText("Ngày sinh (*)");
        jPanel1.add(lblBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));
        jPanel1.add(jDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 150, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nhập thông tin độc giả");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setText("(*) là các trường bắt buộc");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        btnInsert.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/addpeople.jpg"))); // NOI18N
        btnInsert.setText("Thêm độc giả");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 160, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 690, 380));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 630));

        jMenu1.setText("Hệ thống");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem1.setText("Đăng xuất");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Thoát");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reset(){
        txtEmail.setText(null);
        txtCC.setText(null);
        txtTendg.setText(null);
        txtSodt.setText(null);
        jDateChooser.setDate(null);
    }
    
    private boolean checkCC(){
        String st = txtCC.getText();
        if (st.length()!=12) return false;
        for (int i = 0; i<st.length();++i){
            if (st.charAt(i)<'0'||st.charAt(i)>'9') return false;
        }
        return true;
    }
    
    private boolean checkSdt(){
        String st = txtSodt.getText();
        if (st.length()!=10) return false;
        for (int i = 0; i<st.length();++i){
            if (st.charAt(i)<'0'||st.charAt(i)>'9') return false;
        }
        return true;
    }
    
    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
            if (txtTendg.getText().trim().isEmpty()
                || txtSodt.getText().trim().isEmpty()
                || txtEmail.getText().trim().isEmpty()
                || txtCC.getText().trim().isEmpty()
                || jDateChooser.getDate()==null) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ các trường", "Warning", JOptionPane.WARNING_MESSAGE);
            
        }else if (!checkCC()) JOptionPane.showMessageDialog(rootPane, "Căn cước phải gồm 12 chữ số từ 0 - 9", "Warning", JOptionPane.WARNING_MESSAGE);
         else if (!checkSdt()) JOptionPane.showMessageDialog(rootPane, "Số điện thoại phải gồm 10 chữ số từ 0 - 9", "Warning", JOptionPane.WARNING_MESSAGE);
         else {
             if(DocGiaDao.checkEmail(txtEmail.getText())){
            JOptionPane.showMessageDialog(rootPane, "Email đã tồn tại", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            if(DocGiaDao.checkSDT(txtSodt.getText())){
                JOptionPane.showMessageDialog(rootPane, "Số điện thoại đã tồn tại", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            else{
                if(DocGiaDao.checkCCCD(txtCC.getText())){
                    JOptionPane.showMessageDialog(rootPane, "Căn cước công dân đã tồn tại", "Warning", JOptionPane.WARNING_MESSAGE);
                }
                else
            try {
                DocGiaModel dg = new DocGiaModel();
                dg.setMK(txtCC.getText());
                dg.setTendg(txtTendg.getText());
                dg.setSodt(txtSodt.getText());
                dg.setEmail(txtEmail.getText());
                dg.setNgaysinh(jDateChooser.getDate());
                dg.setCancuoccd(txtCC.getText());

                DocGiaDao dao = new DocGiaDao();
                if (dao.insert(dg)) {
                    JOptionPane.showMessageDialog(this, "Thêm mới độc giả thành công!");
                    loadDataToTable();
                    reset();
                } else {
                    JOptionPane.showMessageDialog(this, "Đã có lỗi xảy ra!");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        }
             }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        AdminView adminview = new AdminView(0);
        dispose();
        adminview.setVisible(true);
  //  System.exit(0);
    }//GEN-LAST:event_btnBackActionPerformed

    private void lblClockAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblClockAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblClockAncestorAdded

    private void lblClockAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblClockAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblClockAncestorRemoved

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void txtTendgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTendgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTendgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemDocGiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemDocGiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemDocGiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemDocGiaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemDocGiaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnInsert;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBirth;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JTextField txtCC;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtSodt;
    private javax.swing.JTextField txtTendg;
    // End of variables declaration//GEN-END:variables
}
