/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.qtv;

import dao.DocGiaDao;
import dao.PhieuDao;
import dao.TraSachDao;
import java.sql.Connection;
import database.ConnectDB;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.*;
import static java.time.Instant.now;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.PhieuModel;

/**
 *
 * @author 84899
 */
public class TraSachView extends javax.swing.JFrame {
    int madg;
    List<PhieuModel> phieuList;
    PhieuModel current;
    
    /**
     * Creates new form TraSach
     */
    public TraSachView() {
        initComponents();
        setSize(1000,660);
        phieuList=new ArrayList<PhieuModel>();
        bangmuon.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        bangmuon.getColumnModel().getColumn(0).setPreferredWidth(60);
        bangmuon.getColumnModel().getColumn(1).setPreferredWidth(60);
        bangmuon.getColumnModel().getColumn(3).setPreferredWidth(60);
        bangmuon.getColumnModel().getColumn(4).setPreferredWidth(100);
        bangmuon.getColumnModel().getColumn(5).setPreferredWidth(100);
        bangmuon.getColumnModel().getColumn(6).setPreferredWidth(115);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMadg = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        bangmuon = new javax.swing.JTable();
        lblCambotrong = new javax.swing.JLabel();
        tableName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        masach1Label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hongSpinner = new javax.swing.JSpinner();
        traSachBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        phatPane = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        masachPane = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        txtPhatHong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTongphat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        lblVuilong = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtMadg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 290, 40));

        jLabel1.setText("Nhập mã độc giả (*)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        btnSearch.setText("Hiển thị");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 110, 40));

        bangmuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu", "Mã sách", "Giá bìa", "Số lượng", "Ngày mượn", "Ngày đến hạn", "Số ngày quá hạn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        bangmuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangmuonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(bangmuon);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 580, 180));

        lblCambotrong.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblCambotrong.setForeground(new java.awt.Color(0, 51, 255));
        lblCambotrong.setText("(*) là các trường bắt buộc");
        getContentPane().add(lblCambotrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));

        tableName.setText("Danh sách mượn của ?");
        getContentPane().add(tableName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        masach1Label.setText("Mã sách trả ");
        jPanel2.add(masach1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel5.setText("Số lượng hỏng");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel4.setText("Tiền phạt quá hạn");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        hongSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hongSpinnerStateChanged(evt);
            }
        });
        hongSpinner.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hongSpinnerFocusGained(evt);
            }
        });
        jPanel2.add(hongSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 52, 150, 30));

        traSachBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/returnbook.png"))); // NOI18N
        traSachBtn.setText("Trả sách");
        traSachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traSachBtnActionPerformed(evt);
            }
        });
        jPanel2.add(traSachBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 120, 40));

        jScrollPane3.setViewportView(phatPane);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 150, 30));

        jScrollPane1.setViewportView(masachPane);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 12, 150, 30));

        jLabel2.setText("Tiền phạt sách hỏng");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        jPanel2.add(txtPhatHong, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 150, 30));

        jLabel3.setText("Tổng tiền phạt");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
        jPanel2.add(txtTongphat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 150, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 310, 310));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Trả sách");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        backBtn.setText("< Quay lại");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 510, 90, 30));

        lblVuilong.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblVuilong.setText("Nhấp để chọn phiếu sách muốn trả");
        getContentPane().add(lblVuilong, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1280, 700));

        jMenu1.setText("Hệ thống");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuLogout.setText("Đăng xuất");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(menuLogout);

        menuExit.setText("Thoát");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if(txtMadg.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Mã độc giả không được để trống");
        } else {
            madg=Integer.parseInt(txtMadg.getText());
            if(madg>0)
            updateTable(madg);
        }
    }                                                
    private void updateTable(int madg){
        ConnectDB cn=new ConnectDB();
        Connection conn = cn.getConnection();
        try {
            String sql= "SELECT CURDATE()";
            PreparedStatement ps = (PreparedStatement) conn.prepareCall(sql);
            ResultSet rs=ps.executeQuery();
            rs.next();
            Date today=rs.getDate(1);
            String tendg=DocGiaDao.getNameByMadg(madg);
            tableName.setText("Danh sách mượn của "+tendg);
            phieuList=PhieuDao.findAllNotReturnedOf(madg);
            DefaultTableModel title=new DefaultTableModel(new Object[]
            {"Mã phiếu","Mã sách","Giá bìa", "Số lượng","Ngày mượn","Ngày đến hạn","Số ngày quá hạn"},0);
            for(PhieuModel r:phieuList){
            //madg da co
            int maphieu = r.getMaphieu();
            int masach=r.getMasach();
            int giabia=r.getGiabia();
            int soluong=r.getSoluong();
            String pattern = "yyyy-MM-dd";
            SimpleDateFormat sdf = new SimpleDateFormat(pattern);
            Date ngaymuon=r.getNgaymuon();
            Date ngaydenhan=r.getNgaydenhan();
            long songayquahan=(today.getTime()/(60*60*24*1000)-ngaydenhan.getTime()/(24*60*60*1000));
            if(songayquahan<=0) songayquahan=0;
            title.addRow(new Object[] {maphieu, masach,giabia,soluong,ngaymuon,sdf.format(ngaydenhan),songayquahan});
            }
            bangmuon.setModel(title);
            bangmuon.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            bangmuon.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            bangmuon.getColumnModel().getColumn(0).setPreferredWidth(60);
            bangmuon.getColumnModel().getColumn(1).setPreferredWidth(60);
            bangmuon.getColumnModel().getColumn(3).setPreferredWidth(60);
            bangmuon.getColumnModel().getColumn(4).setPreferredWidth(100);
            bangmuon.getColumnModel().getColumn(5).setPreferredWidth(100);
            bangmuon.getColumnModel().getColumn(6).setPreferredWidth(115);
          if(phieuList.size()==0){
                System.out.println("0");
                JOptionPane.showMessageDialog(this, "Mã độc giả không có sách mượn");
                return;
            }
            }
         catch (Exception e) {
        }
    }
    private void userLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
     
    }//GEN-LAST:event_btnSearchActionPerformed

    private void bangmuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangmuonMouseClicked
        // TODO add your handling code here:
        try {
            int selectedRow = bangmuon.getSelectedRow();
            txtPhatHong.setText("0");
            if (0<=selectedRow && selectedRow < phieuList.size()) {
                            System.out.println(phieuList.size()+"va"+selectedRow);
                current=phieuList.get(selectedRow);
                masachPane.setText(Integer.toString(current.getMasach()));
                int giabia=current.getGiabia();
                long songayquahan=(long)bangmuon.getValueAt(selectedRow,6);
                long tienphat=500*songayquahan+(int)hongSpinner.getValue()*giabia;
                phatPane.setText(Long.toString(500*songayquahan));
                txtTongphat.setText(Long.toString(tienphat));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bangmuonMouseClicked

    private void hongSpinnerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hongSpinnerFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_hongSpinnerFocusGained

    private void hongSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hongSpinnerStateChanged
        // TODO add your handling code here:
        if(current!=null){
            int selectedRow = bangmuon.getSelectedRow();
            int soluong=current.getSoluong();
            if((int)hongSpinner.getValue()>=soluong) hongSpinner.setValue(soluong); 
            if((int)hongSpinner.getValue()<=0) hongSpinner.setValue(0);
            int giabia = current.getGiabia();
            int tienphat = giabia*((int)hongSpinner.getValue());
            txtPhatHong.setText(Long.toString(tienphat));
            int tongphat = Integer.parseInt(phatPane.getText()) + tienphat;
            txtTongphat.setText(Long.toString(tongphat));
        }

        
    }//GEN-LAST:event_hongSpinnerStateChanged

    private void traSachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traSachBtnActionPerformed
         // TODO add your handling code here:
         if (current!=null){
           int maphieu=current.getMaphieu();
           TraSachDao.trasach(maphieu,Integer.parseInt(phatPane.getText()));
           int option = JOptionPane.showConfirmDialog(null,"Xác nhận trả sách?", "Xác nhận", JOptionPane.YES_NO_OPTION);
    if (option == JOptionPane.YES_OPTION) {
                   updateTable(current.getMadg());
    }
         }
    }//GEN-LAST:event_traSachBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        QuanLyMuonTraView muontra = new QuanLyMuonTraView();
        dispose();
        muontra.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TraSachView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable bangmuon;
    private javax.swing.JButton btnSearch;
    private javax.swing.JSpinner hongSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCambotrong;
    private javax.swing.JLabel lblVuilong;
    private javax.swing.JLabel masach1Label;
    private javax.swing.JTextPane masachPane;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JTextPane phatPane;
    private javax.swing.JLabel tableName;
    private javax.swing.JButton traSachBtn;
    private javax.swing.JTextField txtMadg;
    private javax.swing.JTextField txtPhatHong;
    private javax.swing.JTextField txtTongphat;
    // End of variables declaration//GEN-END:variables
}
