/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.docgia;

import view.docgia.DocGiaView;
import dao.LoginDao;
import database.ConnectDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.DocGiaModel;
import view.LoginView;

/**
 *
 * @author 84899
 */
public class ChangPassView extends javax.swing.JFrame {
    DocGiaModel dg;
    public ChangPassView(DocGiaModel dg) {
        this.dg=dg;
        initComponents();
        setSize(600,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblChange = new javax.swing.JLabel();
        lblOldPass = new javax.swing.JLabel();
        txtNewPass = new javax.swing.JPasswordField();
        lblNewPass = new javax.swing.JLabel();
        txtConfirmNewPass = new javax.swing.JPasswordField();
        lblConfirmNewPass = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnUpdatePass = new javax.swing.JButton();
        txtOldPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnLogout = new javax.swing.JMenuItem();
        btnExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblChange.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblChange.setText("Đổi mật khẩu");
        getContentPane().add(lblChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        lblOldPass.setText("Mật khẩu cũ (*)");
        getContentPane().add(lblOldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        txtNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 180, 30));

        lblNewPass.setText("Mật khẩu mới (*)");
        getContentPane().add(lblNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        txtConfirmNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmNewPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtConfirmNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 180, 30));

        lblConfirmNewPass.setText("Nhập lại mật khẩu mới (*)");
        getContentPane().add(lblConfirmNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jButton1.setText("< Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        btnUpdatePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/password.jpg"))); // NOI18N
        btnUpdatePass.setText("Cập nhật mật khẩu");
        btnUpdatePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePassActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdatePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 160, 40));
        getContentPane().add(txtOldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 180, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("(*) là các trường bắt buộc");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 670, 490));

        jMenu1.setText("Hệ thống");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnLogout.setText("Đăng xuất");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(btnLogout);

        btnExit.setText("Thoát");
        jMenu1.add(btnExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdatePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePassActionPerformed
       //Thay doi mk tren CSDL
       String oP = txtOldPass.getText();
       if(txtOldPass.getText().isEmpty() ||
          txtNewPass.getText().isEmpty() ||
          txtConfirmNewPass.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Hãy nhập đủ các trường");
       }
       else if(!oP.equals(dg.getMK())){
            System.out.println("MK:"+dg.getMK()+" "+oP);
            JOptionPane.showMessageDialog(this, "Mật khẩu cũ không chính xác");
       }
       else if (txtNewPass.getText().equals(txtOldPass.getText())){
            JOptionPane.showMessageDialog(this, "Mật khẩu mới ko được trùng mật khẩu cũ");
       }
       else if(!txtNewPass.getText().equals(txtConfirmNewPass.getText())){
            JOptionPane.showMessageDialog(this, "Xác nhận mật khẩu mới không khớp");

       }
       else{
           LoginDao.changePass(dg.getMadg(),txtNewPass.getText());
           JOptionPane.showMessageDialog(this, "Thay đổi thành công");
           DocGiaView docgiaview = new DocGiaView(dg.getMadg());
            dispose();
            docgiaview.setVisible(true);
           txtOldPass.setText("");
           txtNewPass.setText("");
           txtConfirmNewPass.setText("");
       }
    }//GEN-LAST:event_btnUpdatePassActionPerformed

    private void newPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordActionPerformed
        // Nhap mk moi( co the them kiem tra tinh dung dan cua mk moi)
    }//GEN-LAST:event_newPasswordActionPerformed

    private void confirmNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmNewPasswordActionPerformed
        // Kiem tra khop voi mk moi
    }//GEN-LAST:event_confirmNewPasswordActionPerformed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        DocGiaView docgiaview = new DocGiaView(dg.getMadg());
        dispose();
        docgiaview.setVisible(true);
    }//GEN-LAST:event_quitActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnExit;
    private javax.swing.JMenuItem btnLogout;
    private javax.swing.JButton btnUpdatePass;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblChange;
    private javax.swing.JLabel lblConfirmNewPass;
    private javax.swing.JLabel lblNewPass;
    private javax.swing.JLabel lblOldPass;
    private javax.swing.JPasswordField txtConfirmNewPass;
    private javax.swing.JPasswordField txtNewPass;
    private javax.swing.JPasswordField txtOldPass;
    // End of variables declaration//GEN-END:variables
}
