/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.docgia;

import dao.DocGiaDao;
import dao.PhieuDao;
import database.ConnectDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.DocGiaModel;
import model.PhieuModel;
import database.Clock;
import view.LoginView;

/**
 *
 * @author 84899
 */
public class DocGiaView extends javax.swing.JFrame {

    DocGiaModel dg;
    List<PhieuModel> phieuList;
    public DocGiaView(int madg) {
        initComponents();
        setSize(1000,660);
        initClock();
        bangmuon.setAutoCreateRowSorter(true);
        bangmuon.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        bangmuon.getColumnModel().getColumn(0).setPreferredWidth(70);
        bangmuon.getColumnModel().getColumn(1).setPreferredWidth(70);
        bangmuon.getColumnModel().getColumn(3).setPreferredWidth(60);
        bangmuon.getColumnModel().getColumn(4).setPreferredWidth(100);
        bangmuon.getColumnModel().getColumn(5).setPreferredWidth(100);
        bangmuon.getColumnModel().getColumn(6).setPreferredWidth(125);
        bangmuon.getColumnModel().getColumn(7).setPreferredWidth(125);
        phieuList=new ArrayList<PhieuModel>();
        this.dg=DocGiaDao.findByMadg(madg);
        updateTable(madg);
        setInfor();
    }

     private void initClock() {
        Clock th = new Clock(lblClock);
        th.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearchBook = new javax.swing.JButton();
        btnRule = new javax.swing.JButton();
        lblGreeting = new javax.swing.JLabel();
        btnChangePass = new javax.swing.JButton();
        lblClock = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        lblMadg = new javax.swing.JLabel();
        lblNgaysinh = new javax.swing.JLabel();
        lblHoten = new javax.swing.JLabel();
        lblSdt = new javax.swing.JLabel();
        lblCCD = new javax.swing.JLabel();
        txtMadg = new javax.swing.JTextField();
        txtHoten = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtCCCD = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        bangmuon = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNotReturned = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnLogout = new javax.swing.JMenuItem();
        btnExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearchBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/timkiem.png"))); // NOI18N
        btnSearchBook.setText("Tìm kiếm sách");
        btnSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 270, 140, 50));

        btnRule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/qldg.png"))); // NOI18N
        btnRule.setText("Quy định");
        btnRule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRuleActionPerformed(evt);
            }
        });
        getContentPane().add(btnRule, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 340, 140, 50));

        lblGreeting.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblGreeting.setText("Xin chào ?");
        getContentPane().add(lblGreeting, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 380, 50));

        btnChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/password.jpg"))); // NOI18N
        btnChangePass.setText("Đổi mật khẩu");
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });
        getContentPane().add(btnChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 200, 140, 50));

        lblClock.setBackground(new java.awt.Color(204, 255, 204));
        lblClock.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblClock.setText("AM - PM");
        lblClock.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblClockAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                lblClockAncestorRemoved(evt);
            }
        });
        getContentPane().add(lblClock, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmail.setText("Email:");
        jPanel2.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        lblMadg.setText("Mã độc giả:");
        jPanel2.add(lblMadg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        lblNgaysinh.setText("Ngày sinh:");
        jPanel2.add(lblNgaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        lblHoten.setText("Họ và tên:");
        jPanel2.add(lblHoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        lblSdt.setText("Số điện thoại:");
        jPanel2.add(lblSdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        lblCCD.setText("Căn cước công dân");
        jPanel2.add(lblCCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 130, 20));

        txtMadg.setEditable(false);
        jPanel2.add(txtMadg, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 170, 30));

        txtHoten.setEditable(false);
        jPanel2.add(txtHoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 170, 30));

        txtNgaySinh.setEditable(false);
        jPanel2.add(txtNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 170, 30));

        txtSdt.setEditable(false);
        jPanel2.add(txtSdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 170, 30));

        txtEmail.setEditable(false);
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 170, 30));

        txtCCCD.setEditable(false);
        jPanel2.add(txtCCCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 170, 30));

        bangmuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu", "Mã sách", "Giá bìa", "Số lượng", "Ngày mượn", "Ngày đến hạn", "Ngày trả", "Số ngày quá hạn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        bangmuon.setEnabled(false);
        bangmuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangmuonMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(bangmuon);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 740, 160));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        jLabel1.setText("Thông tin độc giả");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Thông tin mượn sách");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        txtNotReturned.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNotReturned.setText("Số sách đang mượn: ");
        jPanel2.add(txtNotReturned, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 780, 450));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("Hệ thống");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnLogout.setText("Đăng xuất");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(btnLogout);

        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jMenu1.add(btnExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setInfor(){
        txtMadg.setText(""+this.dg.getMadg());
        txtHoten.setText(this.dg.getTendg());
        txtNgaySinh.setText(this.dg.getNgaysinh().toString());
        txtSdt.setText(this.dg.getSodt());
        txtCCCD.setText(this.dg.getCancuoccd());
        txtEmail.setText(this.dg.getEmail());
        lblGreeting.setText("Xin chào " + this.dg.getTendg());
        txtNotReturned.setText("Số sách chưa trả: "+PhieuDao.numBookNotReturnOfMadg(this.dg.getMadg()));
        
    }
     private void updateTable(int madg){
        ConnectDB cn=new ConnectDB();
        Connection conn = cn.getConnection();
        try {
            String sql= "SELECT CURDATE()";
            PreparedStatement ps = (PreparedStatement) conn.prepareCall(sql);
            ResultSet rs=ps.executeQuery();
            rs.next();
            Date today=rs.getDate(1);
            String tendg=DocGiaDao.getNameByMadg(madg);
            phieuList=PhieuDao.findAll(madg);
            DefaultTableModel title=new DefaultTableModel(new Object[]
            {"Mã phiếu","Mã sách","Giá bìa", "Số lượng","Ngày mượn","Ngày đến hạn","Ngày trả","Số ngày quá hạn"},0);
            for(PhieuModel r:phieuList){
            //madg da co
            int maphieu = r.getMaphieu();
                System.out.println(maphieu);
            int masach=r.getMasach();
            int giabia=r.getGiabia();
            int soluong=r.getSoluong();
            Date ngaymuon=r.getNgaymuon();
            Object ngaytra;
            if(r.getNgaytra()!=null) {
            ngaytra=r.getNgaytra();
            }else{
             ngaytra="Chưa trả";
            }
            
            String pattern = "yyyy-MM-dd";
            SimpleDateFormat sdf = new SimpleDateFormat(pattern);
            Date ngaydenhan=r.getNgaydenhan();
            long songayquahan=(today.getTime()/(60*60*24*1000)-ngaydenhan.getTime()/(24*60*60*1000));
            if(songayquahan<=0) songayquahan=0;
            
            title.addRow(new Object[] {maphieu, masach,giabia,soluong,sdf.format(ngaymuon),sdf.format(ngaydenhan),ngaytra,songayquahan});
            }
            
            bangmuon.setModel(title);
            bangmuon.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            bangmuon.getColumnModel().getColumn(0).setPreferredWidth(70);
            bangmuon.getColumnModel().getColumn(1).setPreferredWidth(70);
            bangmuon.getColumnModel().getColumn(3).setPreferredWidth(70);
            bangmuon.getColumnModel().getColumn(4).setPreferredWidth(100);
            bangmuon.getColumnModel().getColumn(5).setPreferredWidth(100);
            bangmuon.getColumnModel().getColumn(6).setPreferredWidth(115);
            bangmuon.getColumnModel().getColumn(7).setPreferredWidth(115);
          if(phieuList.size()==0){
                System.out.println("Không có danh sác muon");
                return;
            }
            }
         catch (Exception e) {
        }
    }
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        LoginView lgv = new LoginView();
        dispose();
        lgv.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBookActionPerformed
        view.docgia.TimKiemView timkiem = new view.docgia.TimKiemView(dg.getMadg());
        timkiem.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSearchBookActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        ChangPassView changepass = new ChangPassView(dg);
        changepass.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void btnRuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRuleActionPerformed
        
        String message1 = "1. Chỉnh sửa thông tin cá nhân: Bạn đọc vui lòng đến trưc tiếp đến thư viện \n"
                + "và đăng ký với cán bộ thư viện\n" +
                           "2. Mượn sách:" + "\n" +
                            "  Thời gian mượn tối đa: 30 ngày/1 quyển" + "\n" +
                            "  Tiền phạt quá hạn mượn: 500đ/1 ngày/1 quyển" + "\n" +
                            "  Nếu bạn đọc đang mượn quá 10 quyển, vui lòng trả sách để tiếp tục mượn thêm sách \n"+
                            "3. Trả sách: \n" +
                            "  Phải đảm bảo sách không bị mất trang, dính bẩn, hư hỏng. \n" +
                            "  Nếu sách bị hư hỏng, độc giả phải nộp phạt bằng giá bìa của sách \n" +
                            "4. Khi tạo tài khoản mới, mật khẩu mặc định là số Căn cước công dân \n"
                + "Bạn đọc nên đổi mật khẩu này ngay sau khi tạo tài khoản ";
                            
        JOptionPane.showMessageDialog(new JFrame(), message1, "Quy định thư viện", 0x1);
    }//GEN-LAST:event_btnRuleActionPerformed

    private void lblClockAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblClockAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblClockAncestorAdded

    private void lblClockAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblClockAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblClockAncestorRemoved

    private void bangmuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangmuonMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bangmuonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DocGiaView(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangmuon;
    private javax.swing.JButton btnChangePass;
    private javax.swing.JMenuItem btnExit;
    private javax.swing.JMenuItem btnLogout;
    private javax.swing.JButton btnRule;
    private javax.swing.JButton btnSearchBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCCD;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGreeting;
    private javax.swing.JLabel lblHoten;
    private javax.swing.JLabel lblMadg;
    private javax.swing.JLabel lblNgaysinh;
    private javax.swing.JLabel lblSdt;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtMadg;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JLabel txtNotReturned;
    private javax.swing.JTextField txtSdt;
    // End of variables declaration//GEN-END:variables
}
