/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.docgia;

import dao.SachDao;
import database.ConnectDB;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.SachModel;
import database.Clock;

/**
 *
 * @author 84899
 */
public class TimKiemView extends javax.swing.JFrame {
    private DefaultTableModel tblModel;
    public TimKiemView() {
        initComponents();
        initTableModel();
        setSize(1000,660);
        initClock();
    }
    
    private void initClock() {
        Clock th = new Clock(lblClock);
        th.start();
    }

    private void initTableModel(){
        String[] columnNames = new String[]{"Mã sách", "Tên sách", "Tác giả", "Nhà xuất bản", "Thể loại", "Số lượng còn", "Vị trí", "Giá bìa"};
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(columnNames);
        tbSach.setAutoCreateRowSorter(true);
        tbSach.setModel(tblModel);
        tbSach.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tbSach.getColumnModel().getColumn(0).setPreferredWidth(70);
        tbSach.getColumnModel().getColumn(1).setPreferredWidth(250);
        tbSach.getColumnModel().getColumn(2).setPreferredWidth(120);
        tbSach.getColumnModel().getColumn(3).setPreferredWidth(100);
        tbSach.getColumnModel().getColumn(4).setPreferredWidth(80);
        tbSach.getColumnModel().getColumn(5).setPreferredWidth(100);
        tbSach.getColumnModel().getColumn(6).setPreferredWidth(100);
        tbSach.getColumnModel().getColumn(7).setPreferredWidth(100);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTimkiemtheoten = new javax.swing.JButton();
        btnTimkiemtheotheloai = new javax.swing.JButton();
        txtTimkiem = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSach = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnTimkiemtheotacgia = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnShowall = new javax.swing.JButton();
        lblClock = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnSystem = new javax.swing.JMenu();
        btnLogout = new javax.swing.JMenuItem();
        Thoát = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTimkiemtheoten.setText("Tìm kiếm theo tên");
        btnTimkiemtheoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemtheotenActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimkiemtheoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 150, 30));

        btnTimkiemtheotheloai.setText("Tìm kiếm theo thể loại");
        btnTimkiemtheotheloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemtheotheloaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimkiemtheotheloai, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 150, 30));
        getContentPane().add(txtTimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 530, 40));

        lblSearch.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSearch.setText("Tìm kiếm sách");
        getContentPane().add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 180, 50));

        tbSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbSach.setEnabled(false);
        jScrollPane1.setViewportView(tbSach);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 950, 250));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nhập từ khóa (*)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        btnTimkiemtheotacgia.setText("Tìm kiếm theo tác giả");
        btnTimkiemtheotacgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemtheotacgiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimkiemtheotacgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 150, 30));

        btnBack.setText("< Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, -1, -1));

        btnShowall.setText("Hiển thị tất cả sách");
        btnShowall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowallActionPerformed(evt);
            }
        });
        getContentPane().add(btnShowall, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        lblClock.setBackground(new java.awt.Color(204, 255, 204));
        lblClock.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblClock.setText("AM - PM");
        getContentPane().add(lblClock, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nen-background-trang-dep-va-don-gian_110344503.jpg"))); // NOI18N
        jLabel2.setText("lblBG");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        btnSystem.setText("Hệ thống");
        btnSystem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnLogout.setText("Đăng xuất");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        btnSystem.add(btnLogout);

        Thoát.setText("Thoát");
        Thoát.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThoátActionPerformed(evt);
            }
        });
        btnSystem.add(Thoát);

        jMenuBar1.add(btnSystem);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateTable( List<SachModel> list){
         try{
            tblModel.setRowCount(0);
            if(!list.isEmpty())
            for(SachModel s:list){
                tblModel.addRow(new Object[]{
                s.getMasach(),
                s.getTensach(),
                s.getTentacgia(),
                s.getNxb(),
                s.getTheloai(),
                s.getSoluongconlai(),
                s.getMavitri(),
                s.getGiabia()
            });
            }
            tblModel.fireTableDataChanged();
            
        }
        
        
        catch(Exception e){
            e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    private void btnTimkiemtheotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemtheotenActionPerformed
        // TODO add your handling code here:
        
            List<SachModel> list=SachDao.findAllByName(txtTimkiem.getText());
            updateTable(list);
    }//GEN-LAST:event_btnTimkiemtheotenActionPerformed


    private void btnTimkiemtheotheloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemtheotheloaiActionPerformed
        List<SachModel> list=SachDao.findAllByType(txtTimkiem.getText());
        updateTable(list);
    }//GEN-LAST:event_btnTimkiemtheotheloaiActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        view.LoginView login = new view.LoginView();
        dispose();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void ThoátActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThoátActionPerformed
            dispose();
    }//GEN-LAST:event_ThoátActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
           DocGiaView docgia = new DocGiaView(1);
           dispose();
           docgia.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnShowallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowallActionPerformed
            List<SachModel> list=SachDao.findAll();
            updateTable(list);
    }//GEN-LAST:event_btnShowallActionPerformed

    private void btnTimkiemtheotacgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemtheotacgiaActionPerformed
            List<SachModel> list=SachDao.findAllByAuthor(txtTimkiem.getText());
            updateTable(list);
    }//GEN-LAST:event_btnTimkiemtheotacgiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimKiemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimKiemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimKiemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimKiemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimKiemView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Thoát;
    private javax.swing.JButton btnBack;
    private javax.swing.JMenuItem btnLogout;
    private javax.swing.JButton btnShowall;
    private javax.swing.JMenu btnSystem;
    private javax.swing.JButton btnTimkiemtheotacgia;
    private javax.swing.JButton btnTimkiemtheoten;
    private javax.swing.JButton btnTimkiemtheotheloai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JTable tbSach;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
}
